Repository MichielVanwelsenaere/HomeAutomation.CoDeSys3, pull requests merged in 2023-01, with the labels that each got.

#131 HA Discovery and DMX Dimmers
  .github/pull_request_template.md
  .gitignore
  README.md
  docs/AdditionalFunctionality/DMX_artnet.md
  docs/AdditionalFunctionality/General_HomeAssistant_Discovery.md
  docs/AdditionalFunctionality/General_MQTT.md
  docs/AdditionalFunctionality/MQTT_Birth_and_Last_will_message.md
  docs/CONTRIBUTING.md
  docs/FunctionBlocks/FB_HomeAssistant_DEVICE.md
  docs/FunctionBlocks/FB_MQTT_LOG.md
  docs/FunctionBlocks/FB_OUTPUT_COVER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_DIMMER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_SWITCH_MQTT.md
  docs/FunctionBlocks/FB_VIRTUAL_STRING_MQTT.md
  docs/_img/GettingStartedGuide/Export_all_except_POU.png
  docs/_img/Wireshark_artnet.png
  docs/_img/device_info.jpg
  docs/_img/mqtt_log_in_ha.png
  src/Exports/CodesysV3.export
  src/Exports/PLCopen.xml
  src/HomeAutomation.ecp
  src/Libraries/PRO_JSON 1.0.0.15.library
Labels: enhancement

#135 FB_RS485_DUCO_DUCOBOX
  README.md
  docs/FunctionBlocks/FB_RS485_DUCO_DUCOBOX_MQTT.md
  docs/FunctionBlocks/FB_RS485_ESERA_OWD_MQTT.md
  docs/RS485/datasheets/DUCO_DUCOBOX_Modbus_Registers.pdf
  docs/_drawio/FB_RS485_DUCO_DUCOBOX_MQTT.drawio
  docs/_img/FB_RS485_DUCO_DUCOBOX_MQTT.svg
  src/Exports/CodesysV3.export
  src/Exports/PLCopen.xml
  src/HomeAutomation.ecp
Labels: enhancement

#136 Finetuning docs, incorperating MQTT Discovery badge
  README.md
  docs/AdditionalFunctionality/General_HomeAssistant_Discovery.md
  docs/AdditionalFunctionality/MQTT_Discovery.md
  docs/AdditionalFunctionality/MQTT_General.md
  docs/AdditionalFunctionality/User_leds_Codesys3S_runtime.md
  docs/AdditionalFunctionality/User_leds_éCOCKPIT_runtime.md
  docs/CONTRIBUTING.md
  docs/FAQ/Getting_started_guide_CODESYS_3S.md
  docs/FAQ/Getting_started_guide_éCOCKPIT.md
  docs/FAQ/RS485_tips_and_tricks.md
  docs/FunctionBlocks/FB_HomeAssistant_DEVICE.md
  docs/FunctionBlocks/FB_INPUT_BINARYSENSOR_MQTT.md
  docs/FunctionBlocks/FB_INPUT_PUSHBUTTON_DIMMER_MQTT.md
  docs/FunctionBlocks/FB_INPUT_PUSHBUTTON_MQTT.md
  docs/FunctionBlocks/FB_MQTT_LOG.md
  docs/FunctionBlocks/FB_OUTPUT_BISTABLE_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_COVER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_DIMMER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_SWITCH_MQTT.md
  docs/FunctionBlocks/FB_RS485_BUSCONTROLLER.md
  docs/FunctionBlocks/FB_RS485_DUCO_DUCOBOX_MQTT.md
  docs/FunctionBlocks/FB_RS485_EASTRON_SDM220_MQTT.md
  docs/FunctionBlocks/FB_RS485_EASTRON_SDM_POWER_MQTT.md
  docs/FunctionBlocks/FB_RS485_ESERA_1WIRE_GATEWAY_MQTT.md
  docs/FunctionBlocks/FB_RS485_ESERA_OWD_MQTT.md
  docs/FunctionBlocks/FB_VIRTUAL_BOOL_MQTT.md
  docs/FunctionBlocks/FB_VIRTUAL_INT_MQTT.md
  docs/FunctionBlocks/FB_VIRTUAL_REAL_MQTT.md
  docs/FunctionBlocks/FB_VIRTUAL_STRING_MQTT.md
  docs/RS485/UsingModbusRTU_CODESYS3S.md
  docs/RS485/UsingModbusRTU_éCOCKPIT.md
  docs/SoftwareArchitecture.md
Labels: documentation

#137 FB_OUTPUT_COVER_MQTT: replacing implementation to a more stable one
  docs/FunctionBlocks/FB_INPUT_PUSHBUTTON_MQTT.md
  docs/FunctionBlocks/FB_MQTT_LOG.md
  docs/FunctionBlocks/FB_OUTPUT_BISTABLE_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_COVER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_DIMMER_MQTT.md
  docs/FunctionBlocks/FB_OUTPUT_SWITCH_MQTT.md
  docs/_drawio/FB_OUTPUT_COVER_MQTT.drawio
  docs/_img/FB_OUTPUT_COVER_MQTT.svg
  src/Exports/CodesysV3.export
  src/Exports/PLCopen.xml
  src/HomeAutomation.ecp
Labels: bug

#138 FB_INPUT_BINARYSENSOR_MQTT: supporting MQTT discovery
  docs/FunctionBlocks/FB_INPUT_BINARYSENSOR_MQTT.md
  src/Exports/CodesysV3.export
  src/Exports/PLCopen.xml
  src/HomeAutomation.ecp
Labels: enhancement

#139 Multiple fixes on MQTT discovery
  docs/_img/json_pro_libConfig.jpg
  src/Exports/CodesysV3.export
  src/Exports/PLCopen.xml
  src/HomeAutomation.ecp
Labels: bug
